server:
  port: 8082

spring:
  application:
    name: ms-profesores

  datasource:
    url: jdbc:h2:mem:profesoresdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/universidad/protocol/openid-connect/certs

# Configuración Feign
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
